language: r
sudo: false
cache: packages
r_packages:
- covr
- AER
- betareg
- biglm
- brglm
- caret
- crch
- e1071
- earth
- gam
- gee
- glmx
- kernlab
- lme4
- MASS
- mclogit
- mlogit
- mnlogit
- MNP
- nlme
- nnet
- ordinal
- plm
- pscl
- quantreg
- rpart
- sampleSelection
- survey
- survival
- VGAM
after_success:
- Rscript -e 'library("covr");codecov()'
