language: r
sudo: false
cache: packages
r_packages:
- covr
- AER
- aod
- betareg
- bigFastlm
- biglm
- brglm
- caret
- crch
- e1071
- earth
- ff
- ffbase
- gam
- gee
- glmx
- kernlab
- lme4
- MASS
- mclogit
- mda
- mlogit
- mnlogit
- MNP
- nlme
- nnet
- ordinal
- plm
- pscl
- quantreg
- rpart
- sampleSelection
- speedglm
- survey
- survival
- truncreg
- VGAM
after_success:
- Rscript -e 'library("covr");codecov()'
